# Generated by Django 5.2.3 on 2025-07-03 16:24

import django.db.models.deletion
import questionnaire.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=20)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(max_length=50)),
                ('place_of_residence', models.TextField()),
                ('profession', models.CharField(choices=[('Politicians', 'Politicians'), ('Academician', 'Academician'), ('Scholars', 'Scholars'), ('Researchers', 'Researchers'), ('Journalists', 'Journalists'), ('Activists', 'Activists'), ('MP/MLA', 'MP/MLA'), ('Bureaucrat', 'Bureaucrat'), ('Government Official', 'Government Official'), ('Sitting / Retired Judges', 'Sitting / Retired Judges'), ('Others', 'Others')], max_length=50)),
                ('specialization', models.CharField(choices=[('Constitutional Law', 'Constitutional Law'), ('Political Science', 'Political Science'), ('Public Administration', 'Public Administration'), ('Economics', 'Economics'), ('Other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_id', models.CharField(default=questionnaire.models.generate_application_id, editable=False, max_length=8, unique=True)),
                ('full_downloaded', models.BooleanField(default=False)),
                ('sections_downloaded', models.JSONField(blank=True, default=dict)),
                ('download_option', models.CharField(blank=True, choices=[('FULL', 'Full Questionnaire'), ('SECTION', 'Section-wise')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='response_pdfs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaire.respondent')),
            ],
        ),
    ]
